using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using BaseLib;

namespace DataCenter
{
    class PacketData
	{
        static public void init()
        {
            PacketMgr.me.clear();
            //登陆相关
            addPacket<MSG_CLIENT_LOGINT_2_LS>(MSG_TYPE._MSG_CLIENT_LOGIN_2_LS);
            addUnPacket<MSG_CLIENT_LOGIN_LS_VALIDATE>(MSG_TYPE._MSG_CLIENT_LOGIN_LS_VALIDATE);
            addPacket<MSG_CLIENT_LOGIN_2_GS>(MSG_TYPE._MSG_CLIENT_LOGIN_2_GS);
            addUnPacket<MSG_SERVER_LOGIN_RESPONSE>(MSG_TYPE._MSG_CLIENT_LOGIN_RESPONSE);
            addPacket<MSG_CLIENT_USERINFO_REQUEST>(MSG_TYPE._MSG_CLIENT_USERINFO_REQUEST);
            addUnPacket<MSG_CLIENT_USERINFO_STAR>(MSG_TYPE._MSG_CLIENT_USERINFO_STAR);
            addUnPacket<MSG_CLIENT_USERINFO_FINISH>(MSG_TYPE._MSG_CLIENT_USERINFO_FINISH);          
            addPacket<MSG_CLIENT_CLIENTINITOVER_REQUEST>(MSG_TYPE._MSG_CLIENT_CLIENTINITOVER_REQUEST);
            addPacket<MSG_CLIENT_ACTIVE_REQUEST>(MSG_TYPE._MSG_CLIENT_ACTIVE_REQUEST);
            addUnPacket<MSG_CLIENT_ACTIVE_RESPONSE>(MSG_TYPE._MSG_CLIENT_ACTIVE_RESPONSE);
            addUnPacket<MSG_CLIENT_SERVER_TIME_EVENT>(MSG_TYPE._MSG_CLIENT_SERVER_TIME_EVENT);          

            //角色信息
            addUnPacket<MSG_CLIENT_USER_INFO_EVENT>(MSG_TYPE._MSG_CLIENT_USER_INFO_EVENT);
            addUnPacket<MSG_CLIENT_USER_ATTR_EVENT>(MSG_TYPE._MSG_CLIENT_USER_ATTR_EVENT);
            addUnPacket<MSG_BUY_HERO_SIZE_RESPONSE>(MSG_TYPE._MSG_CLIENT_BUY_HERO_SIZE);

            addPacket<MSG_BUY_POWER_REQUEST>(MSG_TYPE._MSG_CLIENT_BUY_POWER);
            addPacket<MSG_CLIENT_GET_KEY_REQUEST>(MSG_TYPE._MSG_CLIENT_GET_KEY);
            addPacket<MSG_BUY_HERO_SIZE_REQUEST>(MSG_TYPE._MSG_CLIENT_BUY_HERO_SIZE);

            //礼物相关
            addUnPacket<MSG_CLIENT_PRESENT_LST_EVENT>(MSG_TYPE._MSG_CLIENT_PRESENT_LST);
            addUnPacket<MSG_CLIENT_PRESENT_CHANGE_EVENT>(MSG_TYPE._MSG_CLIENT_PRESENT_CHANGE_EVENT);
            addPacket<MSG_CLIENT_GET_PRESENT_REQUEST>(MSG_TYPE._MSG_CLIENT_GET_PRESENT);
            addUnPacket<MSG_CLIENT_GET_PRESENT_RESPONSE>(MSG_TYPE._MSG_CLIENT_GET_PRESENT);

            //英雄
            addUnPacket<MSG_CLIENT_HERO_LST_EVENT>(MSG_TYPE._MSG_CLIENT_HERO_LST_EVENT);
            addUnPacket<MSG_HERO_CHANGE_EVENT>(MSG_TYPE._MSG_CLIENT_HERO_CHANGE_EVENT);
            addPacket<MSG_DIAMOND_ACQUIRE_HERO_REQUEST>(MSG_TYPE._MSG_CLIENT_DIAMOND_ACQUIRE_HERO);
            addPacket<MSG_FRIEND_ACQUIRE_HERO_REQUEST>(MSG_TYPE._MSG_CLIENT_FRIEND_ACQUIRE_HERO);
            addPacket<MSG_HERO_SELL_REQUEST>(MSG_TYPE._MSG_CLIENT_HERO_SELL);
            addPacket<MSG_HERO_EVOLVE_REQUEST>(MSG_TYPE._MSG_CLIENT_HERO_EVOLVE);
            addPacket<MSG_HERO_ENHANCE_REQUEST>(MSG_TYPE._MSG_CLIENT_HERO_ENHANCE);
            addPacket<MSG_HERO_FORMATION_REQUEST>(MSG_TYPE._MSG_CLIENT_HERO_FORMATION);
            addPacket<MSG_HERO_FORMATION_TRIAL_REQUEST>(MSG_TYPE._MSG_CLIENT_HERO_FORMATION_TRIAL);
            addPacket<MSG_HERO_COLLECT_REQUEST>(MSG_TYPE._MSG_CLIENT_HERO_COLLECT);
            addUnPacket<MSG_HERO_ATTR_EVENT>(MSG_TYPE._MSG_CLIENT_HERO_ATTR_EVENT);
            addUnPacket<MSG_HERO_FORMATION_EVENT>(MSG_TYPE._MSG_CLIENT_HERO_FORMATION_EVENT);
            addUnPacket<MSG_HERO_FORMATION_RESPONSE>(MSG_TYPE._MSG_CLIENT_HERO_FORMATION);
            addUnPacket<MSG_HERO_FORMATION_TRIAL_RESPONSE>(MSG_TYPE._MSG_CLIENT_HERO_FORMATION_TRIAL);
            addUnPacket<MSG_DIAMOND_ACQUIRE_HERO_RESPONSE>(MSG_TYPE._MSG_CLIENT_DIAMOND_ACQUIRE_HERO);
            addUnPacket<MSG_FRIEND_ACQUIRE_HERO_RESPONSE>(MSG_TYPE._MSG_CLIENT_FRIEND_ACQUIRE_HERO);
            addUnPacket<MSG_HERO_ENHANCE_RESPONSE>(MSG_TYPE._MSG_CLIENT_HERO_ENHANCE);
            addUnPacket<MSG_HERO_EVOLVE_RESPONSE>(MSG_TYPE._MSG_CLIENT_HERO_EVOLVE);

            addPacket<MSG_ACQUIRE_EXP_FAT_REQUEST>(MSG_TYPE._MSG_CLIENT_ACQUIRE_EXP_FAT);
            addUnPacket<MSG_ACQUIRE_EXP_FAT_RESPONSE>(MSG_TYPE._MSG_CLIENT_ACQUIRE_EXP_FAT);

            //建筑相关
//             addPacket<MSG_BUILDING_BUILD_REQUEST>(MSG_TYPE._MSG_CLIENT_BUILDING_BUILD);
//             addUnPacket<MSG_BUILDING_BUILD_RESPONSE>(MSG_TYPE._MSG_CLIENT_BUILDING_BUILD);
            addPacket<MSG_BUILDING_UPLEV_REQUEST>(MSG_TYPE._MSG_CLIENT_BUILDING_UPLEV);
            addUnPacket<MSG_BUILDING_UPLEV_RESPONSE>(MSG_TYPE._MSG_CLIENT_BUILDING_UPLEV);
            addUnPacket<MSG_BUILDING_LIST_EVENT>(MSG_TYPE._MSG_CLIENT_BUILDING_LIST);
            addUnPacket<MSG_BUILDING_UPDATE_EVENT>(MSG_TYPE._MSG_CLIENT_BUILDING_UPDATE);
            addPacket<MSG_BUILDING_LEVY_REQUEST>(MSG_TYPE._MSG_CLIENT_BUILDING_LEVY);
            addUnPacket<MSG_BUILDING_LEVY_RESPONSE>(MSG_TYPE._MSG_CLIENT_BUILDING_LEVY);

            //道具
            addUnPacket<MSG_ITEM_LIST_EVENT>(MSG_TYPE._MSG_CLIENT_ITEM_LIST_EVENT);
            addUnPacket<MSG_ITEM_UPDATE_EVENT>(MSG_TYPE._MSG_CLIENT_ITEM_UPDATE_EVENT);
            addUnPacket<MSG_ITEM_DELETE_EVENT>(MSG_TYPE._MSG_CLIENT_ITEM_DELETE_EVENT);
            addPacket<MSG_ITEM_SELL_REQUEST>(MSG_TYPE._MSG_CLEINT_ITEM_SELL);
            addUnPacket<MSG_ITEM_SELL_RESPONSE>(MSG_TYPE._MSG_CLEINT_ITEM_SELL);
            addPacket<MSG_SET_BATTLE_IEM_REQUEST>(MSG_TYPE._MSG_CLEINT_SET_BATTLE_IEM);
            addUnPacket<MSG_SET_BATTLE_IEM_RESPONSE>(MSG_TYPE._MSG_CLEINT_SET_BATTLE_IEM);
            addPacket<MSG_BUY_ITEM_SIZE_REQUEST>(MSG_TYPE._MSG_CLEINT_BUY_ITEM_SIZE);
            addUnPacket<MSG_BUY_ITEM_SIZE_RESPONSE>(MSG_TYPE._MSG_CLEINT_BUY_ITEM_SIZE);
            addPacket<MSG_CLEINT_EQUIP_ITEM_REQUEST>(MSG_TYPE._MSG_CLEINT_EQUIP_ITEM);
            addUnPacket<MSG_CLEINT_EQUIP_ITEM_RESPONSE>(MSG_TYPE._MSG_CLEINT_EQUIP_ITEM);
            addPacket<MSG_CLEINT_UNEQUIP_ITEM_REQUEST>(MSG_TYPE._MSG_CLEINT_UNEQUIP_ITEM);
            addUnPacket<MSG_CLEINT_UNEQUIP_ITEM_RESPONSE>(MSG_TYPE._MSG_CLEINT_UNEQUIP_ITEM);
            addPacket<MSG_MAKE_ITEM_BY_FORMULA_REQUEST>(MSG_TYPE._MSG_CLEINT_MAKE_ITEM_BY_FORMULA);
            addUnPacket<MSG_MAKE_ITEM_BY_FORMULA_RESPONSE>(MSG_TYPE._MSG_CLEINT_MAKE_ITEM_BY_FORMULA);
            addPacket<MSG_USE_BATTLE_IEM_REQUEST>(MSG_TYPE._MSG_CLEINT_USE_BATTLE_IEM);
            addUnPacket<MSG_USE_BATTLE_IEM_RESPONSE>(MSG_TYPE._MSG_CLEINT_USE_BATTLE_IEM);

            //好友
            addPacket<MSG_CLIENT_FRIEND_LIST_REQUEST>(MSG_TYPE._MSG_CLIENT_FRIEND_LIST);
            addUnPacket<MSG_CLIENT_FRIEND_LIST>(MSG_TYPE._MSG_CLIENT_FRIEND_LIST);
            addUnPacket<MSG_CLIENT_FRIEND_UPDATE>(MSG_TYPE._MSG_CLIENT_FRIEND_UPDATE);
            addPacket<MSG_CLIENT_FRIEND_APPLY_REQUEST>(MSG_TYPE._MSG_CLIENT_FRIEND_APPLY);
            addUnPacket<MSG_CLIENT_FRIEND_APPLY_RESPONSE>(MSG_TYPE._MSG_CLIENT_FRIEND_APPLY);
            addPacket<MSG_CLIENT_FRIEND_ACCEPT_REQUEST>(MSG_TYPE._MSG_CLIENT_FRIEND_ACCEPT);
            addUnPacket<MSG_CLIENT_FRIEND_ACCEPT_RESPONSE>(MSG_TYPE._MSG_CLIENT_FRIEND_ACCEPT);
            addPacket<MSG_CLIENT_FRIEND_REFUSE_REQUEST>(MSG_TYPE._MSG_CLIENT_FRIEND_REFUSE);
            addUnPacket<MSG_CLIENT_FRIEND_REFUSE_RESPONSE>(MSG_TYPE._MSG_CLIENT_FRIEND_REFUSE);
            addPacket<MSG_CLIENT_FRIEND_DEL_REQUEST>(MSG_TYPE._MSG_CLIENT_FRIEND_DEL);
            addUnPacket<MSG_CLIENT_FRIEND_DEL_RESPONSE>(MSG_TYPE._MSG_CLIENT_FRIEND_DEL);
            addPacket<MSG_CLIENT_SEARCH_USER_REQUEST>(MSG_TYPE._MSG_CLIENT_SEARCH_USER);
            addUnPacket<MSG_CLIENT_SEARCH_USER_RESPONSE>(MSG_TYPE._MSG_CLIENT_SEARCH_USER);
            addPacket<MSG_CLIENT_FRIEND_GIVE_GIFT_REQUEST>(MSG_TYPE._MSG_CLIENT_FRIEND_GIVE_GIFT);
            addUnPacket<MSG_CLIENT_FRIEND_GIVE_GIFT_RESPONSE>(MSG_TYPE._MSG_CLIENT_FRIEND_GIVE_GIFT);
            addPacket<MSG_CLIENT_FRIEND_AWARD_GIFT_REQUEST>(MSG_TYPE._MSG_CLIENT_FRIEND_AWARD_GIFT);
            addUnPacket<MSG_CLIENT_FRIEND_AWARD_GIFT_RESPONSE>(MSG_TYPE._MSG_CLIENT_FRIEND_AWARD_GIFT);
            addUnPacket<MSG_CLIENT_FRIEND_GIFT_LIST>(MSG_TYPE._MSG_CLIENT_FRIEND_GIFT_LIST);
            addUnPacket<MSG_CLIENT_FRIEND_GIFT_DEL>(MSG_TYPE._MSG_CLIENT_FRIEND_GIFT_DEL);
            addPacket<MSG_CLIENT_FRIEND_GIFT_SET_REQUEST>(MSG_TYPE._MSG_CLIENT_FRIEND_GIFT_SET);
            addUnPacket<MSG_CLIENT_FRIEND_GIFT_SET_RESPONSE>(MSG_TYPE._MSG_CLIENT_FRIEND_GIFT_SET);
            addPacket<MSG_CLIENT_FRIEND_CANCEL_APPLY_REQUEST>(MSG_TYPE._MSG_CLIENT_FRIEND_CANCEL_APPLY);
            addUnPacket<MSG_CLIENT_FRIEND_CANCEL_APPLY_RESPONSE>(MSG_TYPE._MSG_CLIENT_FRIEND_CANCEL_APPLY);
            addPacket<MSG_CLIENT_FRIEND_COLLECT_REQUEST>(MSG_TYPE._MSG_CLIENT_FRIEND_COLLECT);
            addUnPacket<MSG_CLIENT_FRIEND_COLLECT_RESPONSE>(MSG_TYPE._MSG_CLIENT_FRIEND_COLLECT);
            addPacket<MSG_CLIENT_FRIEND_GIFT_LIST_REQUEST>(MSG_TYPE._MSG_CLIENT_FRIEND_GIFT_LIST);

            //战斗
            addPacket<MSG_CLIENT_BATTLE_PVE_NORMAL_BATTLE_REQUEST>(MSG_TYPE._MSG_CLIENT_BATTLE_PVE_NORMAL_BATTLE);
            addUnPacket<MSG_CLIENT_BATTLE_PVE_NORMAL_BATTLE_RESPONSE>(MSG_TYPE._MSG_CLIENT_BATTLE_PVE_NORMAL_BATTLE);
            addPacket<MSG_CLIENT_BATTLE_PVE_ACTIVITY_BATTLE_REQUEST>(MSG_TYPE._MSG_CLIENT_BATTLE_PVE_ACTIVITY_BATTLE);
            addUnPacket<MSG_CLIENT_BATTLE_PVE_ACTIVITY_BATTLE_RESPONSE>(MSG_TYPE._MSG_CLIENT_BATTLE_PVE_ACTIVITY_BATTLE);
            addPacket<MSG_CLIENT_BATTLE_PVE_START_REQUEST>(MSG_TYPE._MSG_CLIENT_BATTLE_PVE_START);
            addUnPacket<MSG_CLIENT_BATTLE_PVE_START_RESPONSE>(MSG_TYPE._MSG_CLIENT_BATTLE_PVE_START);
            addUnPacket<MSG_CLIENT_BATTLE_PVE_FIELD_ENEMY_EVENT>(MSG_TYPE._MSG_CLIENT_BATTLE_PVE_FIELD_ENEMY);
            addUnPacket<MSG_CLIENT_BATTLE_PVE_FIELD_MONSTER_CATCH_EVENT>(MSG_TYPE._MSG_CLIENT_BATTLE_PVE_FIELD_MONSTER_CATCH);
            addUnPacket<MSG_CLIENT_BATTLE_PVE_FIELD_DROP_CHESTS_EVENT>(MSG_TYPE._MSG_CLIENT_BATTLE_PVE_FIELD_DROP_CHESTS);
            addUnPacket<MSG_CLIENT_BATTLE_PVE_FIELD_DROP_ITEM_EVENT>(MSG_TYPE._MSG_CLIENT_BATTLE_PVE_FIELD_DROP_ITEM);
            addPacket<MSG_CLIENT_BATTLE_PVE_END_REQUEST>(MSG_TYPE._MSG_CLIENT_BATTLE_PVE_END);
            addUnPacket<MSG_CLIENT_BATTLE_PVE_REWARD_EVENT>(MSG_TYPE._MSG_CLIENT_BATTLE_PVE_REWARD);
            addPacket<MSG_CLIENT_BATTLE_PVE_USER_HELP_REQUEST>(MSG_TYPE._MSG_CLIENT_BATTLE_PVE_USER_HELP);
            addUnPacket<MSG_CLIENT_BATTLE_PVE_USER_HELP_RESPONSE>(MSG_TYPE._MSG_CLIENT_BATTLE_PVE_USER_HELP);

            //竞技场
            addUnPacket<MSG_CLIENT_ARENA_BRIEF_INFO_EVENT>(MSG_TYPE._MSG_CLIENT_ARENA_BRIEF_INFO_EVENT);
            addPacket<MSG_CLIENT_ARENA_TARGET_REQUEST>(MSG_TYPE._MSG_CLIENT_ARENA_TARGET);
            addUnPacket<MSG_CLIENT_ARENA_TARGET_RESPONSE>(MSG_TYPE._MSG_CLIENT_ARENA_TARGET);
            addPacket<MSG_CLIENT_ARENA_PVP_START_REQUEST>(MSG_TYPE._MSG_CLIENT_ARENA_PVP_START);
            addUnPacket<MSG_CLIENT_ARENA_PVP_START_RESPONSE>(MSG_TYPE._MSG_CLIENT_ARENA_PVP_START);
            addUnPacket<MSG_CLIENT_ARENA_TARGET_HERO_INFO_EVENT>(MSG_TYPE._MSG_CLIENT_ARENA_TARGET_HERO_INFO);
            addPacket<MSG_CLIENT_ARENA_PVP_END_REQUEST>(MSG_TYPE._MSG_CLIENT_ARENA_PVP_END);
            addUnPacket<MSG_CLIENT_ARENA_PVP_REWARD_EVENT>(MSG_TYPE._MSG_CLIENT_ARENA_PVP_REWARD);
            addPacket<MSG_CLIENT_ARENA_FRIEND_RANKING_REQUEST>(MSG_TYPE._MSG_CLIENT_ARENA_FRIEND_RANKING);
            addUnPacket<MSG_CLIENT_ARENA_FRIEND_RANKING_RESPONSE>(MSG_TYPE._MSG_CLIENT_ARENA_FRIEND_RANKING);
            addPacket<MSG_CLIENT_ARENA_TOTAL_RANKING_REQUEST>(MSG_TYPE._MSG_CLIENT_ARENA_TOTAL_RANKING);
            addUnPacket<MSG_CLIENT_ARENA_TOTAL_RANKING_RESPONSE>(MSG_TYPE._MSG_CLIENT_ARENA_TOTAL_RANKING);

            addPacket<MSG_CLIENT_ARENA_HERO_FORMATION_REQUEST>(MSG_TYPE._MSG_CLIENT_HERO_FORMATION_ARENA);
            addUnPacket<MSG_CLIENT_ARENA_HERO_FORMATION_RESPONSE>(MSG_TYPE._MSG_CLIENT_HERO_FORMATION_ARENA);
            
            //召唤兽
            addUnPacket<MSG_CLIENT_SUMMON_LST_EVENT>(MSG_TYPE._MSG_CLIENT_SUMMON_LST);
            addPacket<MSG_CLIENT_SUMMON_EVOLVE_REQUEST>(MSG_TYPE._MSG_CLIENT_SUMMON_EVOLVE);
            addUnPacket<MSG_CLIENT_SUMMON_EVOLVE_RESPONSE>(MSG_TYPE._MSG_CLIENT_SUMMON_EVOLVE);
            addUnPacket<MSG_CLIENT_SUMMON_CHANGE_EVENT>(MSG_TYPE._MSG_CLIENT_SUMMON_CHANGE_EVENT);
            addPacket<MSG_CLIENT_SUMMON_UPLVL_REQUEST>(MSG_TYPE._MSG_CLIENT_SUMMON_UPLVL);
            addUnPacket<MSG_CLIENT_SUMMON_UPLVL_RESPONSE>(MSG_TYPE._MSG_CLIENT_SUMMON_UPLVL);
            addPacket<MSG_CLIENT_SUMMON_QUALITY_REQUEST>(MSG_TYPE._MSG_CLIENT_SUMMON_QUALITY);
            addUnPacket<MSG_CLIENT_SUMMON_QUALITY_RESPONSE>(MSG_TYPE._MSG_CLIENT_SUMMON_QUALITY);

            addPacket<MSG_CLIENT_SUMMON_SKILL_UPLVL_REQUEST>(MSG_TYPE._MSG_CLIENT_SUMMON_SKILL_UPLVL);
            addPacket<MSG_CLIENT_SUMMON_UNLOCK_REQUEST>(MSG_TYPE._MSG_CLIENT_SUMMON_UNLOCK);
            addUnPacket<MSG_CLIENT_SUMMON_UNLOCK_RESPONSE>(MSG_TYPE._MSG_CLIENT_SUMMON_UNLOCK);

            //聊天
            addPacket<MSG_CLIENT_CHAT_REQUEST>(MSG_TYPE._MSG_CLIENT_CHAT_REQUEST);
            addUnPacket<MSG_CLIENT_CHAT_RESPONSE>(MSG_TYPE._MSG_CLIENT_CHAT_REQUEST);
            addUnPacket<MSG_CLIENT_CHAT_INFO>(MSG_TYPE._MSG_CLIENT_CHAT_INFO);
            addPacket<MSG_CLIENT_GET_WORLDCHAT_REQUEST>(MSG_TYPE._MSG_CLIENT_GET_WORLDCHAT);
            addUnPacket<MSG_CLIENT_GET_WORLDCHAT_RESPONSE>(MSG_TYPE._MSG_CLIENT_GET_WORLDCHAT);            

            //剧情
            addUnPacket<MSG_CLIENT_STORY_LIST>(MSG_TYPE._MSG_CLIENT_STORY_LIST);
            addUnPacket<MSG_CLIENT_STORY_UPDAE>(MSG_TYPE._MSG_CLIENT_STORY_UPDAE);
            addPacket<MSG_CLIENT_STORY_ACTIVATE_REQUEST>(MSG_TYPE._MSG_CLIENT_STORY_ACTIVATE);
            addUnPacket<MSG_CLIENT_STORY_ACTIVATE_RESPONSE>(MSG_TYPE._MSG_CLIENT_STORY_ACTIVATE);
        }

        static void addPacket<T>(MSG_TYPE id) where T : IPacket, new()
        {
            PacketMgr.me.addPacket<T>((int)id);            
        }

        static void addUnPacket<T>(MSG_TYPE id) where T : IUnPacket, new()
        {
            UnPacketMgr.me.addUnPacket<T>((int)id);
        }
	}
}
