using UnityEngine;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Ps2D
{

    /// <summary>
    /// The document generated by the Photoshop plugin.
    /// </summary>
    [System.Serializable]
    public class LayerMap
    {
        /// <summary>
        /// The version of the document that has been loaded.
        /// </summary>
        public string version { get; set; }

        /// <summary>
        /// Gets the size of this document.
        /// </summary>
        public PixelBounds bounds { get; set; }

        /// <summary>
        /// The root layer that holds all the other layers.
        /// </summary>
        public Layer root { get; set; }

        /// <summary>
        /// A cached version of the layers.
        /// </summary>
        public List<Layer> allLayers { get; set; }

    }

}
